# Generated by Django 6.0.1 on 2026-01-30 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('instance_path', models.CharField(blank=True, max_length=256, null=True)),
                ('file_content', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Instance',
                'verbose_name_plural': 'DICOM Instances',
                'db_table': 'dicom_instance',
            },
        ),
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_time', models.TimeField(blank=True, help_text='Time the study was performed', null=True)),
                ('study_description', models.CharField(blank=True, max_length=256, null=True)),
                ('study_protocol', models.CharField(blank=True, max_length=256, null=True)),
                ('study_modality', models.CharField(blank=True, max_length=256, null=True)),
                ('study_id', models.CharField(blank=True, help_text='Study ID', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Study',
                'verbose_name_plural': 'DICOM Studies',
                'db_table': 'dicom_study',
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-patient_date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('series_root_path', models.CharField(blank=True, max_length=256, null=True)),
                ('frame_of_reference_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('series_description', models.CharField(blank=True, max_length=256, null=True)),
                ('series_date', models.DateField(blank=True, null=True)),
                ('instance_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_instance_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.dicominstance')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.dicomstudy')),
            ],
            options={
                'verbose_name': 'DICOM Series',
                'verbose_name_plural': 'DICOM Series',
                'db_table': 'dicom_series',
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.patient'),
        ),
    ]
