# Generated by Django 6.0.1 on 2026-02-12 12:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('instance_path', models.CharField(blank=True, max_length=256, null=True)),
                ('modality', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Instance',
                'verbose_name_plural': 'DICOM Instances',
                'db_table': 'dicom_instance',
            },
        ),
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_time', models.TimeField(blank=True, help_text='Time the study was performed', null=True)),
                ('study_description', models.CharField(blank=True, max_length=256, null=True)),
                ('study_protocol', models.CharField(blank=True, max_length=256, null=True)),
                ('study_id', models.CharField(blank=True, help_text='Study ID', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Study',
                'verbose_name_plural': 'DICOM Studies',
                'db_table': 'dicom_study',
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
                'ordering': ['-patient_date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='Roi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roi_label', models.CharField(blank=True, max_length=256, null=True)),
                ('roi_id', models.CharField(blank=True, max_length=256, null=True)),
                ('roi_description', models.CharField(blank=True, max_length=256, null=True)),
                ('roi_color', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignment_groups', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='assignment_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('series_root_path', models.CharField(blank=True, max_length=256, null=True)),
                ('frame_of_reference_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('series_description', models.CharField(blank=True, max_length=256, null=True)),
                ('series_date', models.DateField(blank=True, null=True)),
                ('instance_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_instance_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.dicominstance')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.dicomstudy')),
            ],
            options={
                'verbose_name': 'DICOM Series',
                'verbose_name_plural': 'DICOM Series',
                'db_table': 'dicom_series',
            },
        ),
        migrations.CreateModel(
            name='GroupPatientAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='rtstructcompare.assignmentgroup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='rtstructcompare.patient')),
            ],
            options={
                'db_table': 'group_patient_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.patient'),
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rtstructcompare.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roi_label', models.CharField(blank=True, help_text='Common ROI structure name', max_length=256, null=True)),
                ('study_uid', models.CharField(blank=True, help_text='StudyInstanceUID for study-wise ratings', max_length=256, null=True)),
                ('rt1_label', models.CharField(blank=True, help_text='Identifying label for RTSTRUCT 1 (e.g. series description, SOP UID)', max_length=512, null=True)),
                ('rt2_label', models.CharField(blank=True, help_text='Identifying label for RTSTRUCT 2 (e.g. series description, SOP UID)', max_length=512, null=True)),
                ('rt1_sop_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('rt2_sop_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('rt1_rating', models.IntegerField(blank=True, help_text='Rating from 1 to 10 for RTSTRUCT 1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rt2_rating', models.IntegerField(blank=True, help_text='Rating from 1 to 10 for RTSTRUCT 2', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.patient')),
                ('roi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.roi')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTStruct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rtstruct_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.dicominstance')),
            ],
        ),
        migrations.AddField(
            model_name='roi',
            name='rtstruct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.rtstruct'),
        ),
        migrations.AddConstraint(
            model_name='assignmentgroup',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='uniq_assignment_group_name_creator'),
        ),
        migrations.AddConstraint(
            model_name='grouppatientassignment',
            constraint=models.UniqueConstraint(fields=('group', 'patient'), name='uniq_group_patient_assignment'),
        ),
        migrations.AddConstraint(
            model_name='patientassignment',
            constraint=models.UniqueConstraint(fields=('user', 'patient'), name='uniq_patient_assignment_user_patient'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('rt1_sop_uid', 'rt2_sop_uid', 'roi_label'), name='uniq_feedback_user_patient_roi'),
        ),
    ]
