# Generated by Django 5.0.7 on 2026-01-30 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtstructcompare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomstudy',
            name='study_modality',
        ),
        migrations.AddField(
            model_name='dicominstance',
            name='modality',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='RTStruct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rtstruct_instance_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.dicominstance')),
            ],
        ),
        migrations.CreateModel(
            name='Roi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roi_name', models.CharField(blank=True, max_length=256, null=True)),
                ('roi_id', models.CharField(blank=True, max_length=256, null=True)),
                ('roi_description', models.CharField(blank=True, max_length=256, null=True)),
                ('roi_color', models.CharField(blank=True, max_length=256, null=True)),
                ('rtstruct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtstructcompare.rtstruct')),
            ],
        ),
    ]
