# Generated by Django 6.0.1 on 2026-01-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtstructcompare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contourmodificationtypechoices',
            table='contour_modification_type',
        ),
        migrations.AlterModelTable(
            name='dicominstance',
            table='dicom_instance',
        ),
        migrations.AlterModelTable(
            name='dicomseries',
            table='dicom_series',
        ),
        migrations.AlterModelTable(
            name='dicomstudy',
            table='dicom_study',
        ),
        migrations.AlterModelTable(
            name='rtstructurefileimport',
            table='rt_structure_import',
        ),
        migrations.AlterModelTable(
            name='rtstructurefilevoidata',
            table='rt_structure_voi',
        ),
    ]
