# Generated by Django 6.0.1 on 2026-03-11 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtstructcompare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience_post_md_dnb', models.FloatField(verbose_name='Years of experience post MD/DNB')),
                ('specialization_in_breast', models.BooleanField(default=False, verbose_name='Site specialization in breast cancer')),
                ('specialization_in_head_neck', models.BooleanField(default=False, verbose_name='Site specialization in head and neck cancer')),
                ('routinely_segment_brachial_plexus', models.BooleanField(default=False, verbose_name='Routinely segments brachial plexus')),
                ('experience_in_autosegmentation', models.BooleanField(default=False, verbose_name='Experience with an autosegmentation algorithm')),
                ('works_in_teaching_institute', models.BooleanField(default=False, verbose_name='Works in an academic teaching institute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
