# Generated by Django 6.0.1 on 2026-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtstructcompare', '0002_alter_contourmodificationtypechoices_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicominstance',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
